title: My first Blog on GitHub Pages
author: Víctor H. Torres
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a test of blog on GitHub Pages

# social links
twitter_username: victorhtorres # DO NOT include the @ character, or else the build will fail!
github_username:  victorhtorres # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
